employees=[
  {"eid":1,"ename":"Shah Rukh Khan","gender":"Male"},
  {"eid":2,"ename":"Amitabh Bachchan","gender":"Male"},
  {"eid":3,"ename":"Salman Khan","gender":"Male"},
  {"eid":4,"ename":"Aamir Khan","gender":"Male"},
  {"eid":5,"ename":"Akshay Kumar","gender":"Male"},
  {"eid":6,"ename":"Hrithik Roshan","gender":"Male"},
  {"eid":7,"ename":"Ranbir Kapoor","gender":"Male"},
  {"eid":8,"ename":"Ranveer Singh","gender":"Male"},
  {"eid":9,"ename":"Ajay Devgn","gender":"Male"},
  {"eid":10,"ename":"Varun Dhawan","gender":"Male"},
  {"eid":11,"ename":"Deepika Padukone","gender":"Female"},
  {"eid":12,"ename":"Alia Bhatt","gender":"Female"},
  {"eid":13,"ename":"Katrina Kaif","gender":"Female"},
  {"eid":14,"ename":"Priyanka Chopra","gender":"Female"},
  {"eid":15,"ename":"Kareena Kapoor","gender":"Female"},
  {"eid":16,"ename":"Anushka Sharma","gender":"Female"},
  {"eid":17,"ename":"Vidya Balan","gender":"Female"},
  {"eid":18,"ename":"Kangana Ranaut","gender":"Female"},
  {"eid":19,"ename":"Taapsee Pannu","gender":"Female"},
  {"eid":20,"ename":"Kiara Advani","gender":"Female"},
  {"eid":21,"ename":"Rajinikanth","gender":"Male"},
  {"eid":22,"ename":"Kamal Haasan","gender":"Male"},
  {"eid":23,"ename":"Vijay","gender":"Male"},
  {"eid":24,"ename":"Ajith Kumar","gender":"Male"},
  {"eid":25,"ename":"Suriya","gender":"Male"},
  {"eid":26,"ename":"Dhanush","gender":"Male"},
  {"eid":27,"ename":"Vikram","gender":"Male"},
  {"eid":28,"ename":"Prabhas","gender":"Male"},
  {"eid":29,"ename":"Mahesh Babu","gender":"Male"},
  {"eid":30,"ename":"Allu Arjun","gender":"Male"},
  {"eid":31,"ename":"Ram Charan","gender":"Male"},
  {"eid":32,"ename":"Jr NTR","gender":"Male"},
  {"eid":33,"ename":"Pawan Kalyan","gender":"Male"},
  {"eid":34,"ename":"Chiranjeevi","gender":"Male"},
  {"eid":35,"ename":"Nagarjuna","gender":"Male"},
  {"eid":36,"ename":"Venkatesh","gender":"Male"},
  {"eid":37,"ename":"Yash","gender":"Male"},
  {"eid":38,"ename":"Darshan","gender":"Male"},
  {"eid":39,"ename":"Puneeth Rajkumar","gender":"Male"},
  {"eid":40,"ename":"Kichcha Sudeep","gender":"Male"},
  {"eid":41,"ename":"Nayanthara","gender":"Female"},
  {"eid":42,"ename":"Samantha Ruth Prabhu","gender":"Female"},
  {"eid":43,"ename":"Rashmika Mandanna","gender":"Female"},
  {"eid":44,"ename":"Pooja Hegde","gender":"Female"},
  {"eid":45,"ename":"Tamannaah Bhatia","gender":"Female"},
  {"eid":46,"ename":"Sai Pallavi","gender":"Female"},
  {"eid":47,"ename":"Anushka Shetty","gender":"Female"},
  {"eid":48,"ename":"Trisha Krishnan","gender":"Female"},
  {"eid":49,"ename":"Kajal Aggarwal","gender":"Female"},
  {"eid":50,"ename":"Keerthy Suresh","gender":"Female"},
  {"eid":51,"ename":"Sunny Deol","gender":"Male"},
  {"eid":52,"ename":"Bobby Deol","gender":"Male"},
  {"eid":53,"ename":"Sanjay Dutt","gender":"Male"},
  {"eid":54,"ename":"Rishi Kapoor","gender":"Male"},
  {"eid":55,"ename":"Anil Kapoor","gender":"Male"},
  {"eid":56,"ename":"Jackie Shroff","gender":"Male"},
  {"eid":57,"ename":"Saif Ali Khan","gender":"Male"},
  {"eid":58,"ename":"Irrfan Khan","gender":"Male"},
  {"eid":59,"ename":"Nawazuddin Siddiqui","gender":"Male"},
  {"eid":60,"ename":"Pankaj Tripathi","gender":"Male"},
  {"eid":61,"ename":"Madhuri Dixit","gender":"Female"},
  {"eid":62,"ename":"Juhi Chawla","gender":"Female"},
  {"eid":63,"ename":"Rekha","gender":"Female"},
  {"eid":64,"ename":"Sridevi","gender":"Female"},
  {"eid":65,"ename":"Hema Malini","gender":"Female"},
  {"eid":66,"ename":"Rani Mukerji","gender":"Female"},
  {"eid":67,"ename":"Preity Zinta","gender":"Female"},
  {"eid":68,"ename":"Sonam Kapoor","gender":"Female"},
  {"eid":69,"ename":"Shraddha Kapoor","gender":"Female"},
  {"eid":70,"ename":"Jacqueline Fernandez","gender":"Female"},
  {"eid":71,"ename":"Arjun Kapoor","gender":"Male"},
  {"eid":72,"ename":"Sidharth Malhotra","gender":"Male"},
  {"eid":73,"ename":"Tiger Shroff","gender":"Male"},
  {"eid":74,"ename":"Vicky Kaushal","gender":"Male"},
  {"eid":75,"ename":"Ayushmann Khurrana","gender":"Male"},
  {"eid":76,"ename":"Rajkummar Rao","gender":"Male"},
  {"eid":77,"ename":"Kartik Aaryan","gender":"Male"},
  {"eid":78,"ename":"Shahid Kapoor","gender":"Male"},
  {"eid":79,"ename":"Emraan Hashmi","gender":"Male"},
  {"eid":80,"ename":"John Abraham","gender":"Male"},
  {"eid":81,"ename":"Bhumi Pednekar","gender":"Female"},
  {"eid":82,"ename":"Kriti Sanon","gender":"Female"},
  {"eid":83,"ename":"Disha Patani","gender":"Female"},
  {"eid":84,"ename":"Yami Gautam","gender":"Female"},
  {"eid":85,"ename":"Ileana D'Cruz","gender":"Female"},
  {"eid":86,"ename":"Rakul Preet Singh","gender":"Female"},
  {"eid":87,"ename":"Mrunal Thakur","gender":"Female"},
  {"eid":88,"ename":"Tripti Dimri","gender":"Female"},
  {"eid":89,"ename":"Sanya Malhotra","gender":"Female"},
  {"eid":90,"ename":"Fatima Sana Shaikh","gender":"Female"},
  {"eid":91,"ename":"Mohanlal","gender":"Male"},
  {"eid":92,"ename":"Mammootty","gender":"Male"},
  {"eid":93,"ename":"Dulquer Salmaan","gender":"Male"},
  {"eid":94,"ename":"Fahadh Faasil","gender":"Male"},
  {"eid":95,"ename":"Prithviraj Sukumaran","gender":"Male"},
  {"eid":96,"ename":"Nivin Pauly","gender":"Male"},
  {"eid":97,"ename":"Vijay Sethupathi","gender":"Male"},
  {"eid":98,"ename":"Arya","gender":"Male"},
  {"eid":99,"ename":"Silambarasan TR","gender":"Male"},
  {"eid":100,"ename":"Jayam Ravi","gender":"Male"}
]

#with out filter

male_employeees=[]
for emp in employees:
    if emp['gender']=="Male":
        male_employeees.append(emp)

print(len(male_employeees))