a=int(input("Enter First Nunber:"))
b=int(input("Enter First Nunber:"))
print("Sum:", a+b)
print("Difference:", a-b)
print("Product of :", a*b)
print("Division :", a/b)
print("Reminder/Modules Value :", a%b)
print("Floor Division :", a//b)
print("Power of  :", 2**3)